blank_issues_enabled: false
contact_links:
  - name: 💬 - Support and Questions
    url: https://github.com/timbru31/cordova-plugin-lottie-splashscreen/discussions
    about: Please ask and answer questions here.
